spring.application.name=feature-flag-trials
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/featureflags}
spring.datasource.username=${DB_USERNAME:featureflags}
spring.datasource.password=${DB_PASSWORD:featureflags}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI:http://localhost:8081/realms/featureflags}
